p8105_hw1_bx2232
================

``` r
library(moderndive)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

\#Problem 1

``` r
data("early_january_weather")
weather <- early_january_weather
summary(early_january_weather)
```

    ##     origin               year          month        day              hour      
    ##  Length:358         Min.   :2013   Min.   :1   Min.   : 1.000   Min.   : 0.00  
    ##  Class :character   1st Qu.:2013   1st Qu.:1   1st Qu.: 4.000   1st Qu.: 6.00  
    ##  Mode  :character   Median :2013   Median :1   Median : 8.000   Median :11.50  
    ##                     Mean   :2013   Mean   :1   Mean   : 8.039   Mean   :11.53  
    ##                     3rd Qu.:2013   3rd Qu.:1   3rd Qu.:12.000   3rd Qu.:17.75  
    ##                     Max.   :2013   Max.   :1   Max.   :15.000   Max.   :23.00  
    ##                                                                                
    ##       temp            dewp           humid           wind_dir    
    ##  Min.   :24.08   Min.   : 8.96   Min.   : 32.86   Min.   :  0.0  
    ##  1st Qu.:33.98   1st Qu.:19.94   1st Qu.: 51.34   1st Qu.:140.0  
    ##  Median :39.02   Median :26.06   Median : 61.67   Median :240.0  
    ##  Mean   :39.58   Mean   :28.06   Mean   : 65.48   Mean   :208.2  
    ##  3rd Qu.:44.96   3rd Qu.:35.06   3rd Qu.: 78.68   3rd Qu.:290.0  
    ##  Max.   :57.92   Max.   :53.06   Max.   :100.00   Max.   :360.0  
    ##                                                   NA's   :5      
    ##    wind_speed       wind_gust         precip            pressure   
    ##  Min.   : 0.000   Min.   :16.11   Min.   :0.000000   Min.   :1011  
    ##  1st Qu.: 5.754   1st Qu.:19.56   1st Qu.:0.000000   1st Qu.:1018  
    ##  Median : 8.055   Median :21.86   Median :0.000000   Median :1022  
    ##  Mean   : 8.226   Mean   :22.53   Mean   :0.002039   Mean   :1023  
    ##  3rd Qu.:11.508   3rd Qu.:25.32   3rd Qu.:0.000000   3rd Qu.:1027  
    ##  Max.   :24.166   Max.   :31.07   Max.   :0.190000   Max.   :1034  
    ##                   NA's   :308                        NA's   :38    
    ##      visib          time_hour                  
    ##  Min.   : 0.120   Min.   :2013-01-01 01:00:00  
    ##  1st Qu.: 9.000   1st Qu.:2013-01-04 19:15:00  
    ##  Median :10.000   Median :2013-01-08 12:30:00  
    ##  Mean   : 8.515   Mean   :2013-01-08 12:28:09  
    ##  3rd Qu.:10.000   3rd Qu.:2013-01-12 05:45:00  
    ##  Max.   :10.000   Max.   :2013-01-15 23:00:00  
    ## 

``` r
p1 <- ggplot(weather, aes(x = time_hour, y = temp, color = humid)) +
  geom_point(alpha = 0.6) +
  labs(
    x = "Time (hourly)",
    y = "Temperature (°F)",
    color = "Humidity",
    title = "NYC Early January Weather: Temperature over Time"
  ) +
  theme_minimal()
p1
```

![](p8105_hw1_bx2232_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
ggsave("p1_scatter_temp_time.png", plot = p1, width = 7, height = 4)
```

Temperatures show daily cycles; humidity varies over time. Color
gradient helps spot more humid periods.

The `early_january_weather` dataset contains 358 rows and 15 columns.  
The variables include: origin, year, month, day, hour, temp, dewp,
humid, wind_dir, wind_speed, wind_gust, precip, pressure, visib,
time_hour.  
The mean temperature across all observations is 39.58 °F.

\#Problem 2

``` r
n   <- 10
num <- rnorm(n)                               
logi <- num > 0                               
char <- sample(letters, n)                   
fct  <- factor(sample(c("low","med","high"), n, TRUE),
               levels = c("low","med","high"))

df <- tibble(num, logi, char, fct)
df
```

    ## # A tibble: 10 × 4
    ##       num logi  char  fct  
    ##     <dbl> <lgl> <chr> <fct>
    ##  1  1.09  TRUE  q     low  
    ##  2  1.08  TRUE  h     high 
    ##  3 -0.319 FALSE c     med  
    ##  4  2.47  TRUE  s     high 
    ##  5 -0.845 FALSE e     low  
    ##  6  1.32  TRUE  z     med  
    ##  7  0.429 TRUE  n     high 
    ##  8  1.78  TRUE  t     med  
    ##  9 -0.595 FALSE g     high 
    ## 10  0.219 TRUE  f     high

``` r
mean_num  <- mean(df$num)    
mean_logi <- mean(df$logi)   # works; TRUE=1, FALSE=0

list(mean_numeric = mean_num,
     mean_logical = mean_logi)
```

    ## $mean_numeric
    ## [1] 0.6639687
    ## 
    ## $mean_logical
    ## [1] 0.7

``` r
as_numeric_logi <- as.numeric(df$logi)  
as_numeric_char <- suppressWarnings(as.numeric(df$char))  
as_numeric_fct  <- as.numeric(df$fct)  
```
